### ISSUE TITLE
Conversion from string to integer error...

### ISSUE THREAD

**Issue by Thrygon** [Schwaxx/WFInfo#8] opened 2018-07-03 16:23 UTC
[7/3/2018 11:16:04 AM]
System.InvalidCastException: Conversion from string ""Akbolto Prime">Akbolto Prime Ba" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   at WFInfo.Main.VB$StateMachine_124_tPB_Tick.MoveNext()

That is the error I am getting, and I'm hoping to get some help on fixing it.  I looked it up and I do NOT have the knowledge to properly fix it.

**Comment by Schwaxx** [comment] 2018-07-03 18:13
The issue should be fixed now, it was caused by a change on the wiki.

**Closed by Schwaxx** 2018-07-03 18:13 UTC
