### ISSUE TITLE
WFInfo no longer displaying ducat or platinum amounts

### ISSUE THREAD

**Issue by JaneSmith** [Schwaxx/WFInfo#7] opened 2018-06-29 12:54 UTC
Hello. I've used WFInfo in the past and found it to be very useful in relic runs. I haven't used it in a few weeks. I tried it today and now it's no longer displaying ducat or platinum values. The pop-up in the corner now shows something along the lines of, e.g:

> Orthos Prime Blueprint
> Ducks>"Orthos Prime">Orthos Prime

And that's it, repeated in a similar format for each item on the results screen. It does pop-up in the corner, it does detect the right items (usually), but the actual display is just some broken text instead of the important numbers.

I'm using the old style popup if that matters.

Edit: After restarting it, it's now no longer even popping up at all. When I press Print Screen, WFInfo just freezes and I have to kill it from the Task Manager.

Edit 2: It seems like it gets its data from Warframe.Market, which has been extraordinarily slow lately. Could that be why?

**Comment by Schwaxx** [comment] 2018-07-03 18:13
The issue should be fixed now, it was caused by a change on the wiki.

**Closed by Schwaxx** 2018-07-03 18:13 UTC
